In [1]:
import numpy as np

In [2]:
import pandas as pd 


In [16]:
daramad=np.random.randint(5000,15000,12)
daramad

array([14613, 10374,  9514, 12954, 12880, 12210,  6062,  7659, 12229,
       13810,  6684,  8227], dtype=int32)

In [15]:
hazineh=np.random.randint(3000,12000,12)
hazineh

array([11465,  4317,  9769,  3313, 10038,  4632,  3605,  5597,  7762,
        9506, 10127,  8674], dtype=int32)

In [17]:
profit=daramad-hazineh
profit

array([ 3148,  6057,  -255,  9641,  2842,  7578,  2457,  2062,  4467,
        4304, -3443,  -447], dtype=int32)

In [18]:
profit_max=np.max(profit)
profit_max

np.int32(9641)

In [20]:
loss=np.where(profit<0)
loss

(array([ 2, 10, 11]),)