In [ ]:
import numpy as np

In [ ]:
import pandas as pd 


In [ ]:
array_03=np.random.randint(-15,50,size=(7,24))
array_03


array([[36, 39, 11, 23, 30, 26, 26, 32, 24, 10, 19, 37, 38, 39, 36, 12,
        22, 19, 31, 35, 23, 26, 39, 32],
       [35, 11, 39, 26, 13, 37, 33, 38, 34, 18, 39, 14, 11, 16, 29, 20,
        32, 13, 13, 23, 19, 29, 33, 10],
       [15, 30, 12, 28, 22, 14, 11, 29, 28, 36, 11, 29, 10, 14, 14, 29,
        21, 12, 35, 25, 33, 37, 16, 31],
       [25, 26, 32, 28, 29, 34, 27, 38, 29, 10, 34, 12, 38, 31, 10, 29,
        24, 22, 21, 17, 22, 27, 36, 20],
       [38, 22, 33, 21, 18, 14, 31, 15, 11, 39, 39, 30, 16, 23, 33, 10,
        38, 15, 26, 37, 33, 10, 33, 39],
       [34, 17, 16, 12, 15, 32, 11, 29, 14, 10, 20, 39, 16, 31, 39, 14,
        12, 19, 31, 36, 32, 37, 19, 12],
       [37, 17, 25, 39, 19, 24, 23, 14, 18, 25, 28, 27, 24, 22, 14, 11,
        15, 29, 19, 23, 24, 25, 22, 31]], dtype=int32)

In [ ]:
hour_avg = array_03.mean(axis=0)
hour_avg

array([31.42857143, 23.14285714, 24.        , 25.28571429, 20.85714286,
       25.85714286, 23.14285714, 27.85714286, 22.57142857, 21.14285714,
       27.14285714, 26.85714286, 21.85714286, 25.14285714, 25.        ,
       17.85714286, 23.42857143, 18.42857143, 25.14285714, 28.        ,
       26.57142857, 27.28571429, 28.28571429, 25.        ])

In [ ]:
hour_avg.shape  # (24,)
hour_max_temp=np.max(hour_avg)
hour_max_temp

np.float64(31.428571428571427)

In [ ]:
day_avg = array_03.mean(axis=1)
day_avg

array([27.70833333, 24.375     , 22.58333333, 25.875     , 26.        ,
       22.79166667, 23.125     ])

In [ ]:
day_avg.shape  
max_day_avg = np.max(day_avg)
max_day_avg

np.float64(27.708333333333332)

In [ ]:
temp_difference = array_03.max() - array_03.min()
temp_difference

np.int32(29)

In [ ]:
max_hour_avg, max_day_avg, temp_difference
